function [amplitude,phase] = fitSinusoid(time, voluntaryTorque,plotFlag)
%CREATEFIT(TIME,VOLUNTARYTORQUE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : time
%      Y Output: voluntaryTorque
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Sep-2016 06:58:54


%% Fit: 'untitled fit 1'.
if nargin <3
    plotFlag = 0;
end
[xData, yData] = prepareCurveData( time, voluntaryTorque );

% Set up fittype and options.
ft = fittype( 'amplitude * sin (2 * pi *0.1*x+phase)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 -pi];
opts.Upper = [20 pi];
opts.StartPoint = [0.63235924622541 0.0975404049994095];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
amplitude = fitresult.amplitude;
phase = fitresult.phase;
% Plot fit with data.
if plotFlag
    figure( 'Name', 'untitled fit 1' );
    h = plot( fitresult, xData, yData );
    legend( h, 'voluntaryTorque vs. time', 'untitled fit 1', 'Location', 'NorthEast' );
    % Label axes
    xlabel time
    ylabel voluntaryTorque
    grid on
end

